### ISSUE TITLE
Update branches to use latest abapGit version

### ISSUE THREAD

**Issue by mbtools** [SAP-samples/abap-platform-refscen-flight#16]
When using the latest abapGit version to pull the repo to an on-prem system, there are many diffs since the repo branches are not up-to-date to the latest abapGit file formats.

Example:

![image](https://user-images.githubusercontent.com/59966492/235968753-9fdfa9a5-7eed-49e2-853a-cf7d3fef972b.png)

![image](https://user-images.githubusercontent.com/59966492/235969007-ed33ce72-3385-47c0-a056-c8be0e9cff8b.png)

Also, abapGit is supporting namespaces and the `nspc` object is missing in the repo branched.

I highly recommend to update the on-prem branches since the vast majority of users will use a current abapGit version. 

I can do it for `ABAP-platform-2019`. Let me know if you want a PR.

**Comment by MarinaBlank** [comment]
Hi! Thanks for the feedback. 
since we can't know how and when abapGit changes file formats, we do not guarantee that the repository objects have the latest file formats abapGit is using and therfore we do not update the files accordingly.
It shouldn't harm the import if you have Diffs. So you can just go ahead with the import. 

You don't need to import the namespace object. The namespace must be set up in your system prior to the import, so the namespace object is already in your system.
